---
#
#    Debian 8 (jessie) MariaDB10 RDBMS (docker-compose.yml)
#    Copyright (C) 2016-2017 Stafli
#    Lu√≠s Pedro Algarvio
#    This file is part of the Stafli Application Stack.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# For Docker Compose v2+ only
version: '2'

#
# Services
#
services:

  mariadb10:
    labels:
      - "org.label-schema.schema-version=1.0"
      - "org.label-schema.name=$PROJECT_NAME - MariaDB 10.x service"
      - "org.label-schema.description=Based on $PROJECT_FROM - Standard service"
      - "org.label-schema.vendor=$PROJECT_VENDOR"
      - "org.label-schema.url=$PROJECT_URL"
      - "license=$PROJECT_LICENSE"
      - "org.label-schema.vcs-ref=$VCS_REF"
      - "org.label-schema.vcs-url=$VCS_URL"
      - "os-id=$OS_ID"
      - "os-version-id=$OS_VERSION_ID"
      - "architecture=$BUILD_ARCH"
      - "org.label-schema.version=$BUILD_VERSION"
      - "org.label-schema.build-date=$BUILD_DATE"
    image: "stafli/stafli.mariadb.rdbms:debian8_mariadb10"
    build:
      context: "./dockerfiles"
      dockerfile: "mariadb10.dockerfile"
      args:
        app_mariadb_user: "mysql"
        app_mariadb_group: "mysql"
        app_mariadb_home: "/var/lib/mysql"
        app_mariadb_listen_addr: "0.0.0.0"
        app_mariadb_listen_port: "3306"
    logging:
      driver: "json-file"
    networks:
      - backend
    volumes:
      - mariadb10_data:/var/lib/mysql
    ports:
      - "22"
      - "3306"
    working_dir: "/tmp"
    command: "/usr/bin/supervisord -c /etc/supervisor/supervisord.conf --nodaemon"

#
# Networks
#
networks:
  default:
    driver: "bridge"
  backend:
    driver: "bridge"

#
# Volumes
#
volumes:
  mariadb10_data:
    driver: "local"

