---
#
#    Debian 7 (wheezy) MariaDB10 RDBMS (docker-compose.yml)
#    Copyright (C) 2016-2017 Stafli
#    Lu√≠s Pedro Algarvio
#    This file is part of the Stafli Application Stack.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# For Docker Compose v2+ only
version: '2'

#
# Services
#
services:

  rdbms_mariadb10_debian7:
    labels:
      - "description=$PROJECT_NAME, $PROJECT_DESCRIPTION"
      - "maintainer=$PROJECT_AUTHORS_LPALGARVIO_NAME <$PROJECT_AUTHORS_LPALGARVIO_EMAIL>"
      - "org.label-schema.schema-version=1.0.0-rc.1"
      - "org.label-schema.name=$PROJECT_NAME"
      - "org.label-schema.description=$PROJECT_DESCRIPTION"
      - "org.label-schema.keywords=$PROJECT_KEYWORDS"
      - "org.label-schema.url=$PROJECT_URL"
      - "org.label-schema.license=$PROJECT_LICENSE"
      - "org.label-schema.vendor-name=$PROJECT_VENDOR_NAME"
      - "org.label-schema.vendor-email=$PROJECT_VENDOR_EMAIL"
      - "org.label-schema.vendor-website=$PROJECT_VENDOR_WEBSITE"
      - "org.label-schema.authors.lpalgarvio.name=$PROJECT_AUTHORS_LPALGARVIO_NAME"
      - "org.label-schema.authors.lpalgarvio.email=$PROJECT_AUTHORS_LPALGARVIO_EMAIL"
      - "org.label-schema.authors.lpalgarvio.homepage=$PROJECT_AUTHORS_LPALGARVIO_HOMEPAGE"
      - "org.label-schema.authors.lpalgarvio.role=$PROJECT_AUTHORS_LPALGARVIO_ROLE"
      - "org.label-schema.registry-url=$REGISTRY_URL"
      - "org.label-schema.vcs-url=$VCS_URL"
      - "org.label-schema.vcs-ref=$VCS_REF"
      - "org.label-schema.vcs-branch=$VCS_BRANCH"
      - "org.label-schema.os-id=$OS_ID"
      - "org.label-schema.os-version-id=$OS_VERSION_ID"
      - "org.label-schema.os-architecture=$BUILD_ARCH"
      - "org.label-schema.version=$BUILD_VERSION"
      - "org.label-schema.build-date=$BUILD_DATE"
    image: "${IMAGE_URL_PREFIX}:${IMAGE_TAG_PREFIX}${DISTRO_DEBIAN7_VERSION}_${OS_RELEASE_ID}"
    build:
      context: "./dockerfiles"
      dockerfile: "${IMAGE_TAG_PREFIX}${DISTRO_DEBIAN7_VERSION}.dockerfile"
      args:
        app_mariadb_global_user: "mysql"
        app_mariadb_global_group: "mysql"
        app_mariadb_global_home: "/var/lib/mysql"
        app_mariadb_global_loglevel: "notice"
        app_mariadb_global_listen_addr: "0.0.0.0"
        app_mariadb_global_listen_port: "3306"
        app_mariadb_global_default_storage_engine: "InnoDB"
        app_mariadb_global_default_character_set: "utf8"
        app_mariadb_global_default_collation: "utf8_general_ci"
        app_mariadb_tuning_max_connections: "100"
        app_mariadb_tuning_connect_timeout: "5"
        app_mariadb_tuning_wait_timeout: "600"
        app_mariadb_tuning_max_allowed_packet: "128M"
        app_mariadb_tuning_thread_cache_size: "128"
        app_mariadb_tuning_sort_buffer_size: "4M"
        app_mariadb_tuning_bulk_insert_buffer_size: "16M"
        app_mariadb_tuning_tmp_table_size: "32M"
        app_mariadb_tuning_max_heap_table_size: "32M"
        app_mariadb_query_cache_limit: "128K"
        app_mariadb_query_cache_size: "64M"
        app_mariadb_query_cache_min_res_unit: "4k"
        app_mariadb_query_cache_type: "DEMAND"
        app_mariadb_myisam_key_buffer_size: "128M"
        app_mariadb_myisam_open_files_limit: "2000"
        app_mariadb_myisam_table_open_cache: "400"
        app_mariadb_myisam_myisam_sort_buffer_size: "512M"
        app_mariadb_myisam_concurrent_insert: "2"
        app_mariadb_myisam_read_buffer_size: "2M"
        app_mariadb_myisam_read_rnd_buffer_size: "1M"
        app_mariadb_innodb_log_file_size: "50M"
        app_mariadb_innodb_buffer_pool_size: "256M"
        app_mariadb_innodb_buffer_pool_instances: "1"
        app_mariadb_innodb_log_buffer_size: "8M"
        app_mariadb_innodb_file_per_table: "1"
        app_mariadb_innodb_open_files: "400"
        app_mariadb_innodb_io_capacity: "400"
        app_mariadb_innodb_flush_method: "O_DIRECT"
    logging:
      driver: "json-file"
    volumes:
      - rdbms_mariadb10_debian7_data:/var/lib/mysql
    ports:
      - "3306"
    working_dir: "/tmp"
    command: "/usr/bin/supervisord -c /etc/supervisor/supervisord.conf --nodaemon"

#
# Volumes
#
volumes:
  rdbms_mariadb10_debian7_data:
    driver: "local"

